hs_reqwest_0({
  form: {
    portalId: 20632911,
    guid: '3f9fe70f-fb7c-4b7d-a570-c6ef2a6c54ea',
    cssClass: 'hs-form stacked',
    inlineMessage: 'Thanks for submitting the form.',
    redirectUrl: '',
    submitText: 'Submit',
    formFieldGroups: [
      {
        fields: [
          {
            name: 'firstname',
            label: 'First name',
            type: 'string',
            fieldType: 'text',
            description: '',
            groupName: 'contactinformation',
            displayOrder: -1,
            required: false,
            selectedOptions: [],
            options: [],
            validation: {
              name: '',
              message: '',
              data: '',
              useDefaultBlockList: false,
              blockedEmailAddresses: [],
            },
            enabled: true,
            hidden: false,
            defaultValue: '',
            isSmartField: false,
            unselectedLabel: '',
            placeholder: '',
            dependentFieldFilters: [],
            labelHidden: false,
            propertyObjectType: 'CONTACT',
            metaData: [],
            objectTypeId: '0-1',
          },
        ],
        default: true,
        isSmartGroup: false,
        richText: { content: '', type: 'TEXT' },
        isPageBreak: false,
      },
      {
        fields: [
          {
            name: 'email',
            label: 'Email',
            type: 'string',
            fieldType: 'text',
            description: '',
            groupName: 'contactinformation',
            displayOrder: -1,
            required: true,
            selectedOptions: [],
            options: [],
            validation: {
              name: '',
              message: '',
              data: '',
              useDefaultBlockList: false,
              blockedEmailAddresses: [],
            },
            enabled: true,
            hidden: false,
            defaultValue: '',
            isSmartField: false,
            unselectedLabel: '',
            placeholder: '',
            dependentFieldFilters: [],
            labelHidden: false,
            propertyObjectType: 'CONTACT',
            metaData: [],
            objectTypeId: '0-1',
          },
        ],
        default: true,
        isSmartGroup: false,
        richText: { content: '', type: 'TEXT' },
        isPageBreak: false,
      },
    ],
    metaData: [
      { name: 'lang', value: 'en' },
      { name: 'embedType', value: 'REGULAR' },
      { name: 'embedAtTimestamp', value: '1630314891962' },
      { name: 'formDefinitionUpdatedAt', value: '1630187731215' },
    ],
    captchaEnabled: false,
    formTypeNumber: 0,
    thankYouMessageJson: '',
    themeColor: '',
    themeName: 'canvas',
    style:
      '{"fontFamily":"arial, helvetica, sans-serif","backgroundWidth":"100%","labelTextColor":"#33475b","linkColor":"#0000EE","clickedLinkColor":"#551A8B","labelTextSize":"13px","helpTextColor":"#7C98B6","helpTextSize":"11px","legalConsentTextColor":"#33475b","legalConsentTextSize":"14px","thankYouTextColor":"#33475b","thankYouTextSize":"16px","submitColor":"#ff7a59","submitAlignment":"left","submitFontColor":"#ffffff","submitSize":"12px","paginationProgressColor":"#598aff","paginationProgressTextColor":"#33475b","paginationProgressShow":true,"paginationProgressTransition":"fade","paginationProgressTheme":"default","paginationContentUseScroll":false,"paginationContentScrollHeight":"100%"}',
    variantId: null,
    isPublished: true,
  },
  properties: {},
  knownSmartFields: [],
  gates: { viralityVariation: false, useRecaptchaEnterprise: true },
  scopes: { noBranding: false, renderShell: true, rawHtmlAccess: false, customStyleAccess: false },
  time: 1630314891964,
  themeCss:
    '.hs-button{font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;margin:0;cursor:pointer;display:inline-block;font-weight:700;line-height:12px;position:relative;text-align:center;transition:all .15s linear;background-color:#ff7a59;border-color:#ff7a59;color:#fff;border-radius:3px;border-style:solid;border-width:1px;font-size:14px;padding:12px 24px}.hs-button:hover,.hs-button:focus{background-color:#ff8f73;border-color:#ff8f73}.hs-button:active{background-color:#e66e50;border-color:#e66e50}label{font-size:14px;width:130px;color:#33475b;display:block;float:none;width:auto;font-weight:500;line-height:20px;padding-top:0;margin-bottom:4px;font-family:"Helvetica Neue",Helvetica,Arial,sans-serif}.hs-video-form label{color:#fff !important}.hs-video-form .hs-back-button{background-color:#fff;width:20%;height:38px;margin-right:10px;border:1px solid;-webkit-border-radius:3px;-moz-border-radius:3px;-ms-border-radius:3px;border-radius:3px}.hs-video-form .hs-button{width:70%}.hs-video-form .hs-button span{font-size:15px}.hs-video-form .hs-richtext{color:#fff !important}.hs-video-form .legal-consent-container{max-height:180px !important;overflow-y:scroll !important}.hs-video-form .legal-consent-container:after{content:"";display:block;height:100px;width:100%}.hs-video-form .legal-consent-wrapper{position:relative}.hs-video-form .legal-consent-overlay{position:absolute;pointer-events:none;left:0;bottom:0;height:100px;width:100%;background:linear-gradient(to bottom, rgba(255, 255, 255, 0) 0%, #292929 100%)}.hs-error-msgs label{color:#f2545b}.hs-input{display:inline-block;width:90%;max-width:500px;height:40px;padding:9px 10px;font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;font-size:16px;font-weight:normal;line-height:22px;color:#33475b;border:1px solid #cbd6e2;box-sizing:border-box;-webkit-border-radius:3px;-moz-border-radius:3px;-ms-border-radius:3px;border-radius:3px}.hs-input:not([type=file]){background-color:#f5f8fa}.hs-input[type=checkbox],.hs-input[type=radio]{cursor:pointer;width:auto;height:auto;padding:0;margin:3px 5px 3px 0px;line-height:normal;border:none}.hs-input[type=file]{padding:initial;border:initial;line-height:initial;box-shadow:none}select.is-placeholder{color:#bfbfbf}select.is-placeholder:focus{color:#33475b}.hs-input:-moz-placeholder{color:#bfbfbf}.hs-input::-webkit-input-placeholder{color:#bfbfbf}.hs-input option:disabled{color:#bfbfbf}.hs-input input,.hs-input textarea{transition:border .2s linear}.hs-input:focus{outline:none;border-color:rgba(82,168,236,.8)}textarea.hs-input{height:auto}select[multiple].hs-input{height:inherit}input.hs-input.error,div.field.error input,div.field.error textarea,div.field.error .chzn-choices,textarea.hs-input.error,select.hs-input.error{border-color:#c87872}input.hs-input.error:focus,div.field.error input:focus,div.field.error textarea:focus,div.field.error .chzn-choices:focus,textarea.hs-input.error:focus,select.hs-input.error:focus{border-color:#b9554d}.actions{margin-top:18px;margin-bottom:18px;padding:17px 0px}.inputs-list{margin:0 0 5px;width:100%;padding-left:5px}.inputs-list>li{display:block;padding:0;width:100%;padding-top:0}.inputs-list label{float:none;width:auto;padding:0;line-height:18px;white-space:normal;font-weight:normal}.inputs-list:first-child{padding-top:6px}.inputs-list>li+li{padding-top:2px}ul.no-list{list-style:none}.field{margin-bottom:18px}.hs-field-desc{color:#7c98b6;margin:0px 0px 6px;font-size:14px;font-family:"Helvetica Neue",Helvetica,Arial,sans-serif}.hs-form-required{color:red}.hs-richtext{margin-bottom:3px;font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;line-height:24px;font-size:14px;color:#33475b}.hs-richtext hr{margin-left:0;width:91%}.hs-custom-style .hs-dependent-field>div input.hs-input:not([type=checkbox]):not([type=radio]){width:90%}form.hs-form-rtl .field{flex:0 1 100%}form.hs-form-rtl .hs-input[type=checkbox],form.hs-form-rtl .hs-input[type=radio]{margin:3px 5px 3px 5px}form.hs-form-rtl fieldset{display:flex}form.hs-form-rtl fieldset[class^=form-columns-] .input{margin-right:0px}form.hs-form-rtl ul{padding:0px}form.hs-form-rtl .legal-consent-container .hs-form-booleancheckbox-display{display:flex}form.hs-form-rtl .legal-consent-container .hs-form-booleancheckbox-display input{width:auto;float:none}form.hs-form-rtl .legal-consent-container .hs-form-booleancheckbox-display>span{display:inline-block;margin-left:0px}form.hs-form-rtl .hs-dependent-field{display:flex;flex:0 1 100%;flex-wrap:wrap}.email-correction,.email-validation{padding-top:3px;font-size:12px;font-family:"Helvetica Neue",Helvetica,Arial,sans-serif}.email-correction a,.email-validation a{cursor:pointer}@media(max-width: 400px),(min-device-width: 320px)and (max-device-width: 480px){.email-correction form .form-columns-2 .hs-form-field,.email-correction form .form-columns-3 .hs-form-field,.email-validation form .form-columns-2 .hs-form-field,.email-validation form .form-columns-3 .hs-form-field{float:none;width:100%}.email-correction form .form-columns-2 .hs-form-field .hs-input,.email-correction form .form-columns-3 .hs-form-field .hs-input,.email-validation form .form-columns-2 .hs-form-field .hs-input,.email-validation form .form-columns-3 .hs-form-field .hs-input{width:90%}.email-correction form .form-columns-2 .hs-form-field input[type=checkbox],.email-correction form .form-columns-2 .hs-form-field input[type=radio],.email-correction form .form-columns-3 .hs-form-field input[type=checkbox],.email-correction form .form-columns-3 .hs-form-field input[type=radio],.email-validation form .form-columns-2 .hs-form-field input[type=checkbox],.email-validation form .form-columns-2 .hs-form-field input[type=radio],.email-validation form .form-columns-3 .hs-form-field input[type=checkbox],.email-validation form .form-columns-3 .hs-form-field input[type=radio]{width:24px}}.hs-button,.hs-form-field input[type=text],.hs-form-field input[type=email],.hs-form-field input[type=phone],.hs-form-field input[type=number],.hs-form-field input[type=tel],.hs-form-field input[type=date],.hs-form-field textarea{-webkit-appearance:none;-moz-appearance:none}.hs-default-font-element,.hs-main-font-element{font-family:"Helvetica Neue",Helvetica,Arial,sans-serif}',
  globalStyle: null,
  countryCode: 'US',
  errorCode: null,
});
