name: PR Prettier Check

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review

permissions:
  pull-requests: read

jobs:
  ########### LINT PACKAGE ############
  lint-package:
    name: Lint Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - uses: pnpm/action-setup@v2.2.4

      - name: Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.10.0
          cache: 'pnpm'
          registry-url: https://registry.npmjs.org/

      - run: corepack enable

      - name: Install NPM Dependencies
        run: pnpm install --frozen-lockfile

      - name: Prettier Check
        if: ${{ always() }}
        run: pnpm fmt.check
